---
# Playbook to build dependencies for IMC Ansible

- hosts: myteneo
  remote_user: root

  # If you cannot use root, put in your username and choose sudo:yes
  # sudo:yes

  tasks:

  # You may not have easy_install on the system.  Let's install it.
  # This assumes a YUM-based distro.  Change to apt-get if needed
  - name: Install Easy_Install
    yum: name=python-setuptools

  # Next, let's install PIP which will be used to install libs
  - name: Install PIP
    easy_install: name=pip

  # Finally, install XML Parsing library
  - name: Install ElementTree Library
    pip: name=elementtree
